### ISSUE TITLE
Fix spelling and grammar errors in Dialogues

### ISSUE THREAD

**Issue by XHawk87** [Dav-Edward/TachyonsCE#1]
There are a number of spelling and grammar errors in Dialogues. I am creating this issue as a place to report such errors, and log fixes against

**Comment by OrbitalBliss** [comment]
NOT A DIALOG
But, in the controls menu, under MOB COMBAT:
"Press the <CLEAR> button to clear all mob argets<sic>."
&
"Hacking is simmilar<sic> to game"
ALSO
The SYSTEM ICONS don't all fit in the box.

**Comment by Davwyn** [comment]
> NOT A DIALOG
The listed issues are unfortunately out of scope of TachyonCE. We don't have access to the source code to change UI elements and text. We can edit worldgen, dialogs, events, and most assets but not the interface or game engine.
