### ISSUE TITLE
Interested in helping development

### ISSUE THREAD

**Issue by OneVoltTen** [Dav-Edward/TachyonsCE#4]
Hi, I'd be interested in helping development if major issues were listed so I could effectively resolve them.
Otherwise I believe a server list should be in the works for this mod.

**Comment by OneVoltTen** [comment]
Reading the https://itch.io/ forums I could help with:
https://itch.io/t/198561/docker-image-for-the-server
https://itch.io/t/247095/request-raspberry-pi-server * limited
I may host a dedicated server depending on the playerbase.

**Comment by Davwyn** [comment]
Sounds great OneVoltTen,

Sadly designing a server list is beyond the scope of the CE mods as we are not allowed to edit the JAR files that contain the game engine code. We can only modify open files such as the event files, systems files, models, etc.

If you're interested in making a docker image for users that would be good, but in all honesty running a dedicated server is as easy as running the server jar. If you want to create a guide page on how to make a docker image though we can add it to the project page for users.
