### ISSUE TITLE
Difference between this and itch io one

### ISSUE THREAD

**Issue by Polarite** [Dav-Edward/TachyonsCE#6]
I am kind of confused because I cant see the main differences between these two and would be amazing if you could point it out.

the project I mentioned:

https://spektor.itch.io/tachyon

**Comment by Davwyn** [comment]
It's not different. On itch.io the download link for TachyonsCE directly pulls from this repo's newest release.

GitHub is where the source code is kept for when the community wants to add contributions.

Currently CE is far behind from the current Tachyons release.
