### ISSUE TITLE
Credit / link to upstream maybe?

### ISSUE THREAD

**Issue by codefaux** [Dav-Edward/TachyonsCE#7]
New to all this but excited, I found this in a server manager. After browsing everything I can find here, I have no idea what Tachyon FTL is. I'm gonna have to go dig elsewhere. Link your upstream so people who don't already know why they need this project can use it.

**Comment by Davwyn** [comment]
Hi Codefaux. Wow, I never expected anybody to find the GitHub project page on it's own. I'm very under the radar but very, very good point.
The CE Edition of the game is far behind the current version so do please go check it out. I updated the ReadMe but here's the links:
Itch.io page that has the current free Alpha: https://spektor.itch.io/tachyon
Official massively improved Steam version: https://store.steampowered.com/app/1350310/Tachyons_Battles_Across_the_Galaxy/

**Comment by Davwyn** [comment]
If I may ask, what Server Manager did you find mention of this in? I made an EGG file in one many years ago and am very curious if my little contribution is actually still being used. It's amazing to find out when your work is being enjoyed by others like when I found out I helped way more people in the Starbound Server community than I ever realized because of one commenter on my old Reddit post and YouTube video thanking me for fixing the Steam Workshop sync issue on Linux servers.

**Comment by codefaux** [comment]
> Wow, I never expected anybody to find the GitHub project page on it's own. I'm very under the radar but very, very good point.

It's interesting how small the internet can be sometimes, lol. Apologies for what may've been a rather sour tone to my first message, I didn't realize how long yesterday was until I was horizontal and it was apparently showing.


> The CE Edition of the game is far behind the current version so do please go check it out. I updated the ReadMe

Oh, okay. That's good to know as well. I did find the itch.io link after winding up here, but I had no idea who was "newer" -- though it seems like it's worth waiting for the Steam release by now, lol. In the end, the "be the crew" style it presented is less appealing, I was imagining two players on two ships somehow, but I may still just check it out.


> If I may ask, what Server Manager did you find mention of this in? I made an EGG file in one many years ago and am very curious if my little contribution is actually still being used.

You know, that's probably the same. I was browsing a [list](https://github.com/parkervcp/eggs) to see if it was worth investing in Pterodactyl (given its relatively manual installation) and what I presume is yours [here](https://github.com/parkervcp/eggs/tree/master/game_eggs/ftl/tachyon) caught my eye, because I'm a big FTL fan. I can't speak to utilization but it's still there.


> amazing to find out when your work is being enjoyed by others 

Oh for sure, that's a big part of the drive if you ask me. It sure doesn't pay well lol. My "community" was usually just myself and two or three friends, I never really did the public thing. I don't remember if I ever used a Starbound Linux server, but I didn't get very far into modding the game at all. I had a Terraria docker image a few people actually used which fixed server passwords on startup back when that was a thing, but that's about it.

**Comment by Davwyn** [comment]
Ah ha! It was Pterodactyl, I had no idea they incorporated my egg into their GitHub I'm kind of surprised and impressed they deemed it worthy.

Steam version is absolutely worth the wait, but try out the itch.io version to get a taste of it. Especially if you like it, go back to the Itch.io page and check if Spektor is still honoring the "If you pay X dollars, you'll get the Steam version free!" deal as if so you get that huge early supporter discount. Just read the Itch.io page carefully.

Tachyons can be played how you like it. By yourself, with friends working together manning the same ship, or you and your friends manning separate ships. I and my friends had a blast where 8 of us manned 3 ships together and the pirates never knew what hit them. If you want a game where you and as many of your friends want to play however you feel, try it. Tachyons CE in this project was a very early version made to add some much needed features back then and to work with some of my mods that were on the Discord, like the Starwisp mod that was a now abandoned project of mine where I made a NPC helper ship named the Aurora that was set up with a bunch of unique support weapons including ships that were brand new concepts to the game. A mining ship that mined asteroids giving you higher scrap yields, and the Aurora at one point could deploy repair drones to repair your ship while out in space among other quirks like the P.U.C.C ship that got every reviewer that tried it to laugh when Vatish activated it.

I have no idea how (in)compatible my mods are with the current Alpha release but no harm in checking the Discord listed on the itch.io page and see what's going on over there.

Also, no worries about the tone of your first post, but glad there's awesome people like you out there willing to look around try reaching out. Sometimes that makes all the difference for some devs!

Have fun!
